# Generated by Django 4.1.2 on 2022-10-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_last_name_contact_cronico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='visibilidad',
        ),
    ]
