# Generated by Django 4.1.2 on 2022-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_phone_contact_visibilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='bw',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='picos',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='ultimoticket',
        ),
        migrations.AddField(
            model_name='contact',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cronico',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
