# Generated by Django 4.1.2 on 2022-10-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_company_contact_bw_rename_date_contact_picos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picos',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='site',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ultimoticket',
            field=models.CharField(max_length=30),
        ),
    ]
