# Generated by Django 4.1.2 on 2022-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_picos_alter_contact_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='field',
            field=models.BooleanField(default=False),
        ),
    ]
