# Generated by Django 4.1.2 on 2022-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contact_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='field',
        ),
        migrations.AlterField(
            model_name='contact',
            name='clave',
            field=models.BooleanField(default=False, verbose_name='Si'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cronico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
