# Generated by Django 4.1.2 on 2022-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_remove_contact_field_alter_contact_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='clave',
            field=models.BooleanField(default=False),
        ),
    ]
