# Generated by Django 4.1.2 on 2022-10-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_contact_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Enter field documentation', max_length=50),
        ),
    ]
