# Generated by Django 4.1.2 on 2022-10-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='clave',
            field=models.BooleanField(default=False, help_text='Clikear si es cliente clave'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cronico',
            field=models.BooleanField(default=False, help_text='Clikear si es cliente cronico'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='site',
            field=models.BooleanField(default=False, help_text='Clikear si hay otro servicio en el sitio'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibilidad',
            field=models.BooleanField(default=False, help_text='Clikear si es el cliente tiene visibilidad'),
        ),
    ]
