# Generated by Django 4.1.2 on 2022-10-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_alter_contact_clave_alter_contact_cronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='clave',
            field=models.BooleanField(default=False, help_text='Clikear si es cliente clave', verbose_name='Cliente clave?'),
        ),
    ]
