# Generated by Django 4.1.2 on 2022-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_alter_contact_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='bw',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Ancho de banda medio'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cronico',
            field=models.BooleanField(default=False, help_text='Clikear si es cliente cronico', verbose_name='Es cronico?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='picos',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Pico de ancho de banda'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='site',
            field=models.BooleanField(default=False, help_text='Clikear si hay otro servicio en el sitio', verbose_name='Hay otro servicio en el mismo site?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ultimoticket',
            field=models.CharField(max_length=30, verbose_name='Cuando es el ultimo ticket?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibilidad',
            field=models.BooleanField(default=False, help_text='Clikear si es el cliente tiene visibilidad', verbose_name='Tiene visibilidad?'),
        ),
    ]
